const ServiceParameterConstants = {
  PROPERTY_IDENTIFIER_CODE: 0x01,

  EXTENDED_TAG_CODE: 5,

  OPENING_TAG_CODE: 6,

  CLOSING_TAG_CODE: 7,

  // Application Tag: Character String
  CHARACTER_STRING_CODE: 7,

  OBJECT_IDENTIFIER_CODE: 0x04,

  // Application Tag: Enumerated Code
  ENUMERATED_CODE: 9,

  UNKOWN_TAG_NUMBER: 1,

  // Application Tag: Unsigned integer
  UNSIGNED_INTEGER_CODE: 2,

  BOOLEAN_CODE: 1,

  REAL_CODE: 4,

  BACNET_OBJECT_IDENTIFIER: 12,

  EXTENDED_VALUE: 0x05,

  DATE: 0x0a,

  TIME: 0x0b,

  APPLICATION_TAG_BOOLEAN: 0x01,

  APPLICATION_TAG_REAL: 0x04,

  APPLICATION_TAG_DATE: 0x0a,

  APPLICATION_TAG_TIME: 0x0b,

  //    APPLICATION_TAG_OBJECT_IDENTIFIER:4,

  APPLICATION_TAG_NUMBER_CHARACTER_STRING: 7,

  APPLICATION_TAG_NUMBER_BIT_STRING: 8,

  APPLICATION_TAG_BACNET_OBJECT_IDENTIFIER: 12,

  SIGNED_INTEGER_TWOS_COMMPLEMENT_NOTATION: 3,
};

module.exports = { ServiceParameterConstants };
